spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memsourceprojects
    username: memsourceprojects
    password: memsource_pw
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    baseline-on-migrate: true

sample:
  client:
    url: https://cloud.memsource.com/web/api2/v1

application:
  authentication:
    jwtsecret: memsourcesecret